// Generated by Xata Codegen 0.26.9. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "Users",
    columns: [
      { name: "ip", type: "string" },
      { name: "agent", type: "string" },
      { name: "country", type: "string" },
      { name: "city", type: "string" },
      { name: "platform", type: "string" },
      { name: "os", type: "string" },
      { name: "device", type: "string" },
    ],
  },
  {
    name: "Page_Views",
    columns: [
      { name: "user_id", type: "string" },
      { name: "url", type: "string" },
      { name: "referral_url", type: "string" },
    ],
  },
  {
    name: "User_Events",
    columns: [
      { name: "user_id", type: "string" },
      { name: "name", type: "string" },
      { name: "data", type: "text" },
    ],
  },
  {
    name: "Referrals",
    columns: [
      { name: "referral_url", type: "string" },
      { name: "source_url", type: "string" },
    ],
  },
  {
    name: "Geographic_Locations",
    columns: [
      { name: "code", type: "string" },
      { name: "name", type: "string" },
      { name: "region", type: "string" },
      { name: "city", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Users = InferredTypes["Users"];
export type UsersRecord = Users & XataRecord;

export type PageViews = InferredTypes["Page_Views"];
export type PageViewsRecord = PageViews & XataRecord;

export type UserEvents = InferredTypes["User_Events"];
export type UserEventsRecord = UserEvents & XataRecord;

export type Referrals = InferredTypes["Referrals"];
export type ReferralsRecord = Referrals & XataRecord;

export type GeographicLocations = InferredTypes["Geographic_Locations"];
export type GeographicLocationsRecord = GeographicLocations & XataRecord;

export type DatabaseSchema = {
  Users: UsersRecord;
  Page_Views: PageViewsRecord;
  User_Events: UserEventsRecord;
  Referrals: ReferralsRecord;
  Geographic_Locations: GeographicLocationsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://smail-Yarar-s-workspace-r4lqpv.eu-central-1.xata.sh/db/the-analytics",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
